#!/usr/bin/env bash

echo -e "input the url you want to download"
read PAGE

wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --no-parent \
         $PAGE
